### PR TITLE
Add support for testing `aws-hosted-cp`

### PR DESCRIPTION
**Pull request by squizzi**
Note: This PR was intentionally created on a repository branch instead of my fork so we can iterate on the e2e testing workflow and then change it to `pull_request_target` for merge.

---

* Break KubeClient helpers into provider specific file
* Finish aws-hosted-cp test and add comments through test to make it
  easier to understand.
* Use GinkgoHelper across e2e tests, populate hosted vars from
  AWSCluster.
* No longer rely on local registry for images in test/e2e.
* Support OS for awscli install.
* Prepend hostname to collected log artifacts.
* Support no cleanup of provider specs, differentiate ci
  cluster names.
* Add docs on running tests, do not wait for all providers
  if configured.
* Reinstantiate resource validation map on each instance of
  validation.
* Enable the external-gc feature via annotation, featureGate
  bool. (Closes: https://github.com/Mirantis/hmc/issues/152)
* Bump aws-*-cp templates to 0.1.3
* Bump cluster-api-provider-aws template to 0.1.2
* Improve test logging to log template name and validation
  phase.
* Bump k0s version to v1.30.4+k0s.0, set CCM nodeSelector to
  null for aws-hosted-cp. (Closes: https://github.com/Mirantis/hmc/issues/290)
* Break cleanup into seperate job so that it is unaffected by
  concurrency group cancellations.

Closes: #212

### CODE REVIEW

**Comment by squizzi** [comment]
Welp, running the tests locally seems to work ok, but GitHub actions consistently encounters: `NatGatewaysReconciliationFailed` :\

**Comment by squizzi** [comment]
I was able to fix the nuke behavior so we reliably cleanup EIP's now which helps the behavior but concurrent running tests will fail because of the allocation limit.  I just need to figure out #290 and this should be done.  It's definitely ready for review.

**Comment by squizzi** [comment]
Currently failing in Deletion validation and reproducing the VPC dependency violation bug, I'll probably comment those tests out with a fixme because they'll never pass otherwise.

**Comment by slysunkin** [comment]
> Currently failing in Deletion validation and reproducing the VPC dependency violation bug, I'll probably comment those tests out with a fixme because they'll never pass otherwise.

We already have bug #152 for AWS VPC

**Comment by squizzi** [comment]
Heads up to reviewers:  The tests are failing as they've revealed two issues: #152 and #290.  The testing code itself isn't problematic though.

**Comment by squizzi** [comment]
I've removed the CCM tests for the hosted-cp temporarily so we can test cluster deletions via CI.  I intend to bring them back before merge.

**Comment by squizzi** [comment]
It appears cancelled tests will not run the cleanup resources workflow, which is concerning since we could get into a state where our test gets cancelled by a subsequent PR push and then the AWS resources are never cleaned.  I'll need to look into the best way to handle this case since the `if: always()` declaration doesn't appear to work in this situation.

**Comment by squizzi** [comment]
> It appears cancelled tests will not run the cleanup resources job, which is concerning since we could get into a state where our test gets cancelled by a subsequent PR push and then the AWS resources are never cleaned. I'll need to look into the best way to handle this case since the if: always() declaration doesn't appear to work in this situation.

I think I have an idea of how to fix this, I can make the `e2etest` job concurrent and then have a cleanup job that runs as `always()`, we'll see if this works...

**Comment by squizzi** [comment]
I've squash and pushed all of the changes since no one has reviewed this yet.  In summary the squashed commit resolves all of the outstanding issues and fixes the cancellation issue.  We just need @slysunkin 's merge in #229 so I can rebase and that should fix the deletions that are stuck for both hosted and standalone templates ... _hopefully_ 

Looking forward to that green checkmark.

**Comment by squizzi** [comment]
I put the other make steps for `dev-aws-nuke` in the PHONY nooooooo 🤦‍♂️

**Comment by squizzi** [comment]
I pulled @slysunkin 's changes in and CI is running, hopefully things are good 🤞

**Comment by squizzi** [comment]
Last test failed in secret generation, that's a new one.

```
E0914 20:07:27.884717       1 controller.go:329] "Reconciler error" err="failed to add &Node{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:NodeSpec{PodCIDR:,DoNotUseExternalID:,ProviderID:,Unschedulable:false,Taints:[]Taint{},ConfigSource:nil,PodCIDRs:[],},Status:NodeStatus{Capacity:ResourceList{},Allocatable:ResourceList{},Phase:,Conditions:[]NodeCondition{},Addresses:[]NodeAddress{},DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:0,},},NodeInfo:NodeSystemInfo{MachineID:,SystemUUID:,BootID:,KernelVersion:,OSImage:,ContainerRuntimeVersion:,KubeletVersion:,KubeProxyVersion:,OperatingSystem:,Architecture:,},Images:[]ContainerImage{},VolumesInUse:[],VolumesAttached:[]AttachedVolume{},Config:nil,},} watch on cluster hmc-system/ci-1726339710-e2e-test-hosted: failed to create cluster accessor: error fetching REST client config for remote cluster \"hmc-system/ci-1726339710-e2e-test-hosted\": failed to retrieve kubeconfig secret for Cluster hmc-system/ci-1726339710-e2e-test-hosted: Secret \"ci-1726339710-e2e-test-hosted-kubeconfig\" not found" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="hmc-system/ci-1726339710-e2e-test-hosted-md-6dx4q-cnzvf" namespace="hmc-system" name="ci-1726339710-e2e-test-hosted-md-6dx4q-cnzvf" reconcileID="e4dfb466-766a-4267-9c3d-ca3b30e0992d"
```

**Comment by squizzi** [comment]
Almost there, seeing a failure to delete standalone now with:

```
I0916 20:53:12.723064       1 cleanup.go:64] "deleting aws resources created by tenant cluster" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="hmc-system/ci-1726517368-e2e-test" namespace="hmc-system" name="ci-1726517368-e2e-test" reconcileID="22e48f35-85e1-4a5c-97d5-7b116922050d" cluster="ci-1726517368-e2e-test"
I0916 20:53:12.723081       1 cleanup.go:97] "get aws resources created by tenant cluster with resource group tagging API" controller="awscluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSCluster" AWSCluster="hmc-system/ci-1726517368-e2e-test" namespace="hmc-system" name="ci-1726517368-e2e-test" reconcileID="22e48f35-85e1-4a5c-97d5-7b116922050d" cluster="ci-1726517368-e2e-test"
E0916 20:53:13.726802       1 controller.go:329] "Reconciler error" err=<
	error deleting network: failed to detach internet gateway "igw-0b4456b73e77a2f65": DependencyViolation: Network vpc-0829721ee4d5f7b15 has some mapped public address(es). Please unmap those public address(es) before detaching the gateway.
```

**Comment by squizzi** [comment]
I've commented out the deletion test for standalone for a couple of reasons:
1. The IGW bug here: https://github.com/Mirantis/hmc/pull/280#issuecomment-2354046567 is intermittent, but even if we get past that we eventually run into issues reconciling the `AWSMachine`'s due to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4120 almost every single time.
2. We're already testing deleting of an AWS template via our `aws-hosted-cp` test which covers HMC's involvement in the deletion process relatively well.  We can work in a follow-up once 4120 above is resolved or perhaps work on a workaround in a follow-up.
3. There's a bunch of e2e test work that would benefit from the changes in this PR and I've worked through a ton of issues to get to a pretty much green result, minus a deletion test with outstanding known bugs.

**Review by Kshatrix — APPROVED** [review]

**Pull request merged**
