### PR TITLE
Bundled beachhead services: cert-manager, external-secrets, velero, dex

### PR DESCRIPTION
**Pull request by BROngineer**
Added:
- cert-manager v1.16.2 service template
- external-secrets v0.11.0 service template
- velero v8.1.0 service template
- dex v0.19.1 service template

Fixes: #736 #737 #738 #739

### CODE REVIEW

**Review by wahabmk — APPROVED** [review]

**Comment by DinaBelova** [comment]
@wahabmk just to confirm, did you try this PR / tested the service templates?

**Comment by wahabmk** [comment]
Yes I can see that the serviceTemplates have been installed:
```
➜  hmc git:(fc1cfae) ~ khmc get servicetemplate
NAME                      VALID
cert-manager-1-16-2       true
dex-0-19-1                true
external-secrets-0-11-0   true
ingress-nginx-4-11-0      true
ingress-nginx-4-11-3      true
kyverno-3-2-6             true
velero-8-1-0              true
```

**Review by wahabmk — APPROVED** [review]

**Comment by BROngineer** [comment]
Draft until testing deployments using added templates completed. Need to figure out whether services are usable with default values, or minimal required configuration. If the minimal required configuration is user-specific ([Dex](https://artifacthub.io/packages/helm/dex/dex#getting-started)) or requires credentials ([Velero](https://artifacthub.io/packages/helm/vmware-tanzu/velero#provider-credentials)) or requires CRDs (cert-manager) then it should be written in docs.

**Comment by BROngineer** [comment]
Since service templates only provides references to charts and do not allow to pre-define chart values, I'd consider the PR as ready to be merged.

**Review by a13x5 — APPROVED** [review]
LGTM

Really nitpicking: CRs at the end of some files are missing (up to author to fix this)

And please **squash** commits before merging

**Review by eromanova — APPROVED** [review]

**Review by Kshatrix — APPROVED** [review]

**Pull request merged**
